#!/bin/bash

RES=0
echo -n "- Checking nginx conf generation..."
if test "${MFBUS_NGINX_PORT}" -le 1024; then
    echo_nok
    echo_bold "=> You can't use a value < 1024 as [nginx]/port"
    echo_bold "=> Fix your configuration"
    RES=1
else
    _make_nginx_conf >/dev/null 2>&1
    if test $? -eq 0; then
        echo_ok
    else
        echo_nok
        RES=1
    fi
fi
exit ${RES}
