include root.mk
include $(MFEXT_HOME)/share/subdir_root.mk
include $(MFCOM_HOME)/share/startup_scripts_profiles.mk

all:: profiles $(PREFIX)/bin/cronwrap.sh $(PREFIX)/bin/mfbus.status $(PREFIX)/bin/mfbus.start $(PREFIX)/bin/mfbus.stop $(PREFIX)/bin/mfbus.init load_env
