###################
##### STARTUP #####
###################
[startup]

flag=1

###############
##### LOG #####
###############
[log]

# log retention (in days)
retention=5

# log default level
# (NOTSET, DEBUG => everything)
#  INFO => everything but not DEBUG)
#  WARNING => everything but not DEBUG and INFO)
#  CRITICAL => everything but not DEBUG, INFO AND WARNING)
default_level=INFO
default_level[DEV]=NOTSET

[circus]
endpoint=ipc://{{MODULE_RUNTIME_HOME}}/var/circus.socket
pubsub_endpoint=ipc://{{MODULE_RUNTIME_HOME}}/var/circus_pubsub.socket

[admin]
# null => no monitoring
hostname=localhost
influxdb_http_port=18086

[redis]
# redis max memory (in mega bytes)
max_memory=100

[nginx]
port=12568
proxy_temp_path={{MODULE_RUNTIME_HOME}}/tmp/nginx/proxy_temp
clientbody_temp_path={{MODULE_RUNTIME_HOME}}/tmp/nginx/clientbody_temp

[tmp_blob_store]


# Storage dir
storage_dir={{MODULE_RUNTIME_HOME}}/var/tmp_blob_store

# Default blob lifetime (in seconds)
default_lifetime=300

# Maximum blob lifetime (in seconds)
max_lifetime=3600

# Maximum blob size (in bytes)
max_blob_size=104857600

# Maximum number of blobs in a given namespace
# (< 0 => unlimited)
max_namespace_size=-1

# Maximum total size of blobs in a given namespace
# (< 0 => unlimited)
max_namespace_size_in_bytes=-1

# Persist state on disk every configured seconds
# (< 0 => no persistance on disk)
persistance_every=-1
