 include {{MFEXT_HOME}}/opt/core/share/redis.conf     

 pidfile ""
 port 0
 tcp-backlog 40000
 timeout 600
 tcp-keepalive 10
 {% if MFBUS_TMP_BLOB_STORE_PERSISTANCE_EVERY|int >= 0 %}
 save {{MFBUS_TMP_BLOB_STORE_PERSISTANCE_EVERY}} 1
 dbfilename redis_dump.rdb
 {% endif %}
 dir {{MODULE_RUNTIME_HOME}}/var/
 unixsocket {{MODULE_RUNTIME_HOME}}/var/redis.socket
 maxmemory {{MFBUS_REDIS_MAX_MEMORY}}mb
 maxmemory-policy allkeys-lru
 lua-time-limit 300000
